[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[tools]
bun = "latest"
"cargo:just-lsp" = "latest"
deno = "latest"
go = "latest"
"go:github.com/wader/jq-lsp" = "latest"
java = "oracle-graalvm-21.0.7"
maven = "latest"
node = "latest"
"npm:@abhiz123/todoist-mcp-server" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:awk-language-server" = "latest"
"npm:better-commits" = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:tombi" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
pnpm = "10.8.1"
python = "3.13.4"
sbt = "1.10.11"
uv = "latest"
yarn = "latest"
